spring:
  application:
    name: user-service
  config:
    import: "optional:file:.env[.properties]"

  # MongoDB
  data:
    mongodb:
      host: localhost
      port: 27017
      database: rent-a-car-user
  # PostgreSQL
  datasource:
    postgres:
      url: jdbc:postgresql://localhost:5432/rent-a-car-user
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: 123456

  jpa:
    postgres:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
      hibernate:
        ddl-auto: update

  # Security & Keycloak Ayarları (değişmeden kalıyor)
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}   # realm bilgisi
          jwk-set-uri: ${JWT_ISSUER_URI}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: ${CLIENT_ID}   # client bilgisi
      principle-attribute: ${PRINCIPLE_ATTRIBUTE}

keycloak:
  auth-server-url: ${ADMIN_AUTH_URL}
  realm: ${REALM}
  resource: ${CLIENT_ID}
  credentials:
    secret: ${CLIENT_SECRET}
  admin-username: ${KEYCLOAK_ADMIN_USERNAME}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD}

server:
  port: 8282
logging:
  level:
    org.springframework.data.mongodb: DEBUG
    com.mongodb: DEBUG
    com.keycloak: DEBUG