

package com.tahaakocer.user_service.Soap;
//------------------------------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 9.3.3.2
//
// Created by Quasar Development 
//
// This class has been generated for test purposes only and cannot be used in any commercial project.
// To use it in commercial project, you need to generate this class again with Premium account.
// Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
//
// Licence: 9AEA2E6C3CE2CC4D4DC893FAA660F91A29CEB1D1BBCE867CF9F4C3C308CC90A11113BB642E205617A7D6315D7B22AADF619B71DDC1F1D7B32CF94D98C7315168
//------------------------------------------------------------------------

public class MNHSoapException extends java.lang.Exception
{
    private org.w3c.dom.Element _details=null;
    private Object _fault = null;
    
    public MNHSoapException(String message,org.w3c.dom.Element details)
    {
        super(message);
        _details=details;
    }

    public MNHSoapException(Object fault)
    {
        _fault=fault;
    }

    public Object getFault() {
        return _fault;
    }


    public org.w3c.dom.Element getDetails() {
        return _details;
    }
}